# Generated by Django 5.0.4 on 2024-04-15 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fornecedor', models.CharField(max_length=200, verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Fornecedors',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_despesa', models.DateField(verbose_name='Data')),
                ('descricao_despesa', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor_despesa', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor')),
                ('nome_fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.fornecedor')),
            ],
            options={
                'verbose_name': 'Despesas',
                'verbose_name_plural': 'Despesas',
            },
        ),
    ]
