# Generated by Django 5.0.4 on 2024-04-15 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='nome_fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.fornecedor', verbose_name='Fornecedor'),
        ),
    ]
