# Generated by Django 5.0.4 on 2024-04-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_despesa_nome_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='valor_despesa',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor'),
        ),
    ]
