# Generated by Django 5.0.4 on 2024-04-18 23:27

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_despesa_nome_fornecedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despesa',
            options={'verbose_name_plural': 'Despesas'},
        ),
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AddField(
            model_name='despesa',
            name='quant_despesa',
            field=models.IntegerField(default=1, verbose_name='Quantidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='despesa',
            name='total_despesa',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('quant_despesa'), '*', models.F('valor_despesa')), output_field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor Total')),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='valor_despesa',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor Total'),
        ),
    ]
