# Generated by Django 5.0.4 on 2024-04-24 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_despesa_options_alter_fornecedor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despesa',
            options={'ordering': ['data_despesa'], 'verbose_name_plural': 'Despesas'},
        ),
    ]
