# Generated by Django 5.0.4 on 2024-04-25 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_alter_despesa_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despesa',
            options={'ordering': ['-data_despesa'], 'verbose_name_plural': 'Despesas'},
        ),
    ]
