# Generated by Django 5.0.4 on 2024-04-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_alter_despesa_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='data_despesa',
            field=models.DateField(auto_now_add=True, verbose_name='Data'),
        ),
    ]
