# Generated by Django 5.0.4 on 2024-04-28 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_alter_despesa_data_despesa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
    ]
