# Generated by Django 5.0.4 on 2024-04-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_alter_fornecedor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='despesa',
            options={'ordering': ['-data_despesa'], 'verbose_name': 'Despesa', 'verbose_name_plural': 'Despesas'},
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome_fornecedor',
            field=models.CharField(max_length=200, verbose_name='forn'),
        ),
    ]
