# Generated by Django 5.0.4 on 2024-04-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_alter_despesa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='nome_fornecedor',
            field=models.CharField(max_length=200, verbose_name='Fornecedor'),
        ),
    ]
