# Generated by Django 5.0.4 on 2024-04-29 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_alter_fornecedor_nome_fornecedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'ordering': ['nome_fornecedor'], 'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
    ]
