# Generated by Django 5.0.4 on 2024-04-29 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_alter_fornecedor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'ordering': ['-pk'], 'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
    ]
